# Generated by Django 3.2.9 on 2021-11-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=150, verbose_name='Вид контакт')),
            ],
            options={
                'verbose_name': 'Вид Контакт',
                'verbose_name_plural': 'Видове Контакти',
                'ordering': ('contact_type',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Име на контакт')),
                ('contact_phone_1', models.CharField(max_length=200, verbose_name='Телефон 1')),
                ('contact_phone_2', models.CharField(blank=True, max_length=200, verbose_name='Телефон 2')),
                ('contact_mail_1', models.CharField(max_length=200, verbose_name='Електронен адрес 1')),
                ('contact_mail_2', models.CharField(blank=True, max_length=200, verbose_name='Електронен адрес 2')),
                ('contact_gender', models.CharField(choices=[('f', 'Жена'), ('m', 'Мъж')], default='m', max_length=1)),
                ('contact_note', models.CharField(blank=True, max_length=350, verbose_name='Бележки')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kontakti.contacttype', verbose_name='Вид контакт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
                'ordering': ('contact_name',),
            },
        ),
    ]
