# Generated by Django 3.2.9 on 2021-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontakti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_gender',
            field=models.CharField(choices=[('f', 'Жена'), ('m', 'Мъж')], default='m', max_length=1, verbose_name='Пол'),
        ),
    ]
