# Generated by Django 3.2.9 on 2022-03-16 19:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaintGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Жанр Картина',
                'verbose_name_plural': 'Жанрове Картини',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид Картина',
                'verbose_name_plural': 'Видове Картини',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SculpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид Скулптура',
                'verbose_name_plural': 'Видове Скулптура',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sculptures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заглавие')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание на Скулптурата')),
                ('year', models.IntegerField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.authors', verbose_name='Автор')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.sculptype', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Скулптура',
                'verbose_name_plural': 'Скулптури',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заглавие')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание на Картината')),
                ('year', models.IntegerField(blank=True)),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.authors', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.paintgenre', verbose_name='Жанр')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.painttype', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картини',
                'ordering': ('title',),
            },
        ),
    ]
