# Generated by Django 3.0.4 on 2021-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_mail_2',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Електронен адрес 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_2',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Телефон 2'),
        ),
    ]
